### PR TITLE
Add lombok support

### PR DESCRIPTION
**Pull request by yoyosource**
### Checklist:

- [x] If this PR is a new feature, please provide at least one example link
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by yoyosource** [comment]
Now really for the main branch.

**Comment by yoyosource** [comment]
My bad, the last PullRequest was not to the main branch.

**Comment by stefanbuck** [comment]
> My bad, the last PullRequest was not to the main branch.

Ohh, was reviewing the PR on my phone and didn't pay attention to the target branch. I'm glad you've noticed it

**Comment by yoyosource** [comment]
Now it just need to build again.

**Pull request merged**
