### PR TITLE
Expand .net/nuget support for .targets files and FrameworkReferences

### LINKED ISSUE #784: NuGet support for .targets files
It's been awhile since I last looked at this code so I wanted to check on this before diving in. Along with the `.csproj` and `.props` file extensions `.targets` can also contain NuGet references. Is this just a matter of adding the extension to the list here? Are there any tests that need to be added/updated?

https://github.com/OctoLinker/OctoLinker/blob/93d85161cd3eacac9ad467dcdd55075a2566a224/packages/plugin-dot-net/index.js#L16

This is an example of a `.targets` file with `PackageReference`s in it.

https://github.com/SixLabors/ImageSharp.Web/blob/4a49f4d5c582d66dde963aa3eb5d88bdd5313491/Directory.Build.targets

There's a difference in the format used in these files as well. The `.props` files use `<PackageReference Include=""/>` while `.targets` is using `<PackageReference Update="" />`.

### PR DESCRIPTION
**Pull request by xt0rted**
### Checklist:

- [x] If this PR is a new feature, please provide at least one example link
- [x] Make sure all of the significant new logic is covered by tests

Here's a list of files that can be used to verify these changes:

- https://github.com/SixLabors/ImageSharp.Web/blob/4a49f4d5c582d66dde963aa3eb5d88bdd5313491/src/ImageSharp.Web/ImageSharp.Web.csproj#L14-L30
- https://github.com/SixLabors/ImageSharp.Web/blob/4a49f4d5c582d66dde963aa3eb5d88bdd5313491/Directory.Build.props#L99-L105
- https://github.com/SixLabors/ImageSharp.Web/blob/4a49f4d5c582d66dde963aa3eb5d88bdd5313491/Directory.Build.targets#L19-L42
-

Closes #784

### CODE REVIEW

**Comment by xt0rted** [comment]
@stefanbuck I added a `.csproj`, `.props`, and `.targets` file under `/e2e/dotnet` along with the annotations. Running `npm run build; npm run e2e` (in powershell) results in the following error:

```
> OctoLinker@5.2.6 e2e C:\dev\xt0rted\OctoLinker
> node ./e2e/generate-fixtures-json.js && jest --config=e2e/jest-e2e.config.js

Fixtures root: https://github.com/OctoLinker/OctoLinker/blob/master/e2e
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\dev\xt0rted\OctoLinker\e2e
  11 files checked.
  testMatch: C:/dev/xt0rted/OctoLinker/e2e/**\?(*.)test?(s).js - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 11 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! OctoLinker@5.2.6 e2e: `node ./e2e/generate-fixtures-json.js && jest --config=e2e/jest-e2e.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the OctoLinker@5.2.6 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brian\AppData\Roaming\npm-cache\_logs\2020-01-24T21_40_54_674Z-debug.log
```

I'm seeing the new entries showing up in the `fixtures.json` file, but the tests don't seem to run. I also backed out my changes and tried running just the existing tests and I get the same result. Did I miss a step?

**Comment by stefanbuck** [comment]
Ohhh right, locally `npm run e2e` runs against https://github.com/OctoLinker/OctoLinker/tree/master. Just push the fixtures and the CI will use your fork instead of OctoLinker/master.

**Comment by stefanbuck** [comment]
Early next week I'll a new major release which will include this change as well

**Comment by stefanbuck** [comment]
I feel like you have helped out this repo quite a bit, thank you for that, I added you as a maintainer of the repo. Let me know if you have any questions or concerns.

**Comment by xt0rted** [comment]
Thanks, I'm happy to help.

**Comment by stefanbuck** [comment]
Just to let you know, I had to limit your write access since tagging master will automatically release a new version. I need to verify that you're not a robot first 😉

**Comment by xt0rted** [comment]
@stefanbuck I just noticed that not all of the items are being linkified when viewing the files tab ([example](https://github.com/OctoLinker/OctoLinker/pull/785/files#diff-9222904f7ff80fd69544d107fbf18b0a)), but if you view the individual files they are ([example](https://github.com/xt0rted/OctoLinker/blob/6681d3563393b7bfd677af15b5b442e90c075288/e2e/fixtures/dotnet/Directory.Build.props)). Are there limitations for the diff view or is this a bug?

**Comment by stefanbuck** [comment]
Good spot. Looks like a bug to me. I'm busy with other stuff tonight, but a brief look shows that [matches](https://github.com/OctoLinker/OctoLinker/blob/a2063e4f5734c7bae0dfebdafdde759565eba3f0/packages/core/app.js#L40) contains just 20 results. The `blob` array seems to be fine so I guess the RegEx matching isn't working for some reason. Do you have time to look at this?

**Comment by xt0rted** [comment]
I won't have time until the weekend, but I can take a look then.

**Comment by stefanbuck** [comment]
No worries, it's not super critical. If you want we can pair up on this  and jump on a call. Just send me a DM on twitter and we will see if we both are available at some point.

**Comment by stefanbuck** [comment]
@xt0rted good news, I was able to narrow down issue and will raise a PR later today with more details

**Pull request merged**
