### PR TITLE
Add all new clickable imports

### PR DESCRIPTION
**Pull request by yoyosource**
### Checklist:

- [x] If this PR is a new feature, please provide at least one example link
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

**Comment by yoyosource** [comment]
I hope this includes everything needed.

**Review by stefanbuck — APPROVED** [review]
Looks good to me

**Comment by stefanbuck** [comment]
Thanks for taking the time to add the required changes

**Comment by yoyosource** [comment]
Any idea, when this goes live?

**Comment by stefanbuck** [comment]
> Any idea, when this goes live?

Can't 100% commit but maybe Wednesday, latest Thursday. There is another change I would like to include in the next release.

**Comment by stefanbuck** [comment]
I applied the label `invalid` here, just to be inline with the hacktoberfest guidelines (in case you participate)

**Comment by yoyosource** [comment]
> I applied the label invalid here, just to be inline with the hacktoberfest guidelines (in case you participate)

What is the hacktoberfest? I did not hear from it till now.

**Comment by stefanbuck** [comment]
https://hacktoberfest.digitalocean.com/ 😉

**Comment by yoyosource** [comment]
Thanks.

**Pull request merged**
