### PR TITLE
Enable lombok imports in java plugin

### PR DESCRIPTION
**Pull request by stefanbuck**
Counterpart of https://github.com/OctoLinker/api/pull/373

OctoLinker supports just a subset of java imports in order to avoid putting to much unnecessary load on the API. Therefore java imports supported by the API needs be added to the allow list. 

There is one caveat. Other java packages starting with `lombok` will also match e.g. `lombokeee`, but this shouldn't be a huge deal given that `lombok` is quite specific.

### CODE REVIEW

**Comment by yoyosource** [comment]
Just another side not I did not just add Lombok, also added a few more along the way, so this PR is not complete.

**Comment by yoyosource** [comment]
```
  'http://projectlombok.org/api/allclasses-frame.html',
   'http://www.atteo.org/static/classindex/apidocs/allclasses-frame.html',
   'https://asm.ow2.io/javadoc/allclasses-index.html',
   'http://hamcrest.org/JavaHamcrest/javadoc/2.2/allclasses-frame.html',
   'http://logback.qos.ch/apidocs/allclasses-frame.html',
   'http://yoyosource.github.io/YAPION/javadoc/v0.25.3/allclasses-index.html',
```
This is the complete list of what I added.

**Comment by stefanbuck** [comment]
> Just another side not I did not just add Lombok, also added a few more along the way, so this PR is not complete.

Thanks for the hint. Will look into it tomorrow.

**Comment by stefanbuck** [comment]
Or actually if you want to give it a try feel free to cherry pick this change an great a new PR with the additional changes. Please ignore the failing end 2 end test, I'll fix them

**Comment by yoyosource** [comment]
> Or actually if you want to give it a try feel free to cherry pick this change an great a new PR with the additional changes. Please ignore the failing end 2 end test, I'll fix them

I will try it thanks.

**Comment by yoyosource** [comment]
Ok created the PullRequest.

**Comment by yoyosource** [comment]
The other PullRequest was just to this branch.

**Pull request closed without merging**
