### PR TITLE
Add Codecov

### PR DESCRIPTION
**Pull request by stefanbuck**
Note: I branched off from #489 to get a working build

Configure this project to report code coverage using codecov https://codecov.io/gh/OctoLinker/OctoLinker

### CODE REVIEW

**Comment by josephfrazier** [comment]
Hmm, it can't hurt, right? Is it configured to require PRs to include coverage?

**Comment by stefanbuck** [comment]
No, it shouldn't hurt. 

> Is it configured to require PRs to include coverage?

No, I don't think so. I didn't set up anything in this direction. Btw. are your sure that codecov supports this or was it just a general question?

**Comment by josephfrazier** [comment]
I'm not completely sure, but I think it's possible to require PRs to not decrease coverage. I doubt that's the default though, so we should be good.

**Comment by stefanbuck** [comment]
I quickly scanned their docs, but I couldn't find anything. https://docs.codecov.io/docs/codecov-yaml

Anyway, let's see if this works for us. We can easily remove it anytime. Thanks for your feedback

**Comment by josephfrazier** [comment]
Of course, I'm looking forward to seeing how it goes!

**Pull request merged**
