### PR TITLE
Add project sdk support for .net

### PR DESCRIPTION
**Pull request by xt0rted**
### Checklist:

- [x] If this PR is a new feature, please provide at least one example link
- [x] Make sure all of the significant new logic is covered by tests

This builds on #785 so the `Sdk` attribute is also handled now.

### CODE REVIEW

**Comment by stefanbuck** [comment]
CI stucks , most likely caused by the force push. Maybe best to recreate the commit from scratch

**Comment by xt0rted** [comment]
It wasn't running before the force push. The workflow might need to be adjusted to something like this:

```yml
on:
  push:
    branches:
      - master
  pull_request:
```

That's how I set it up for [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark/blob/master/.github/workflows/main.yml) so it'd handle pushes to master, PRs from local branches, and PRs from forks.

**Comment by stefanbuck** [comment]
A few minutes ago I remove the `pull_request` flag https://github.com/OctoLinker/OctoLinker/commit/8feff6fbec9b5d0d6a530403a1428d76c53a4eeb since I was annoyed by the extra run 😆 Thanks for sharing this template. Will update the workflow straight away

**Comment by stefanbuck** [comment]
done

**Comment by xt0rted** [comment]
@stefanbuck I forgot the sdk value could contain multiple values like this `Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish"`. Is it possible to split these and create a link for each one?

**Comment by stefanbuck** [comment]
That might be tricky.  I need to look into this myself before I can say anything useful 😉

**Comment by stefanbuck** [comment]
I looked into it and it's rather complicated to make this work. The current OctoLinker architecture is based on the assumption that each RegExp returns just one result. Changing this requires some larger rewrites down the line. Most likely not worth the effort.

**Comment by xt0rted** [comment]
From what I know having multiple values for this isn't common. I've never seen it done in a project outside of my own so I doubt many people would hit this.

**Pull request merged**
